export const businessRules = {
    MAX_TASKS_PER_COLUMN: 50,
    MAX_COLUMNS_PER_BOARD: 20,
    MAX_BOARDS_PER_USER: 15,
    
    MAX_TASK_DESCRIPTION_LENGTH: 1000,

    MAX_TASK_TITLE_LENGTH: 150,
    MAX_COLUMN_TITLE_LENGTH: 150,
    MAX_BOARD_TITLE_LENGTH: 150,

    MAX_PASSWORD_LENGTH: 50,
    MAX_EMAIL_LENGTH: 255,
    MAX_USERNAME_LENGTH: 100
}