import { IBoardRepository } from "../../domain/repositories/IBoardRepository";
import { Board } from "../../domain/entities/Board";

interface CreateBoardRequest {
  title: string;
  ownerId: string;
}

export class CreateBoard {
  constructor(private boardRepository: IBoardRepository) {}

  async execute(request: CreateBoardRequest): Promise<Board> {
    if (!request.title) {
      throw new Error("Board title is required");
    }

    // Create entity (ID is generated by DB usually, passing empty string for now or use UUID if preferred)
    const board = new Board("", request.title, request.ownerId, [], new Date());
    
    return await this.boardRepository.create(board);
  }
}